# Generated by Django 3.2.6 on 2023-01-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usagedata',
            unique_together={('username', 'mac_address', 'start_time')},
        ),
    ]
